# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-l9umRm2e5_DLpndU1h3cTWg8LNLAoF
"""

import os
import urllib.request
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

def run_preprocessing():
    # 1. Setup path
    # Menggunakan relative path dengan asumsi skrip dijalankan dari dalam folder 'preprocessing'
    raw_folder = '../heart_disease_raw'
    clean_folder = 'heart_disease_preprocessing'

    os.makedirs(raw_folder, exist_ok=True)
    os.makedirs(clean_folder, exist_ok=True)

    raw_path = os.path.join(raw_folder, 'heart_disease.csv')
    clean_path = os.path.join(clean_folder, 'dataset_clean.csv')

    # 2. Unduh Data jika belum ada
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
    if not os.path.exists(raw_path):
        print("Mengunduh data raw...")
        urllib.request.urlretrieve(url, raw_path)

    columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
               'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

    # 3. Memuat Data
    print("Memuat dataset...")
    df = pd.read_csv(raw_path, names=columns)

    # 4. Preprocessing
    print("Melakukan data cleaning dan scaling...")
    df.replace('?', np.nan, inplace=True)

    # Perbaikan tipe data
    df['ca'] = pd.to_numeric(df['ca'], errors='coerce')
    df['thal'] = pd.to_numeric(df['thal'], errors='coerce')

    # Pengisian missing value
    df['ca'] = df['ca'].fillna(df['ca'].median())
    df['thal'] = df['thal'].fillna(df['thal'].median())

    # Ubah target
    df['target'] = df['target'].apply(lambda x: 1 if x > 0 else 0)

    # Scaling
    scaler = StandardScaler()
    num_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
    df[num_cols] = scaler.fit_transform(df[num_cols])

if __name__ == '__main__':
    run_preprocessing()